name: Deployment to GitHub Pages

on:
  # call this workflow when the workflow Main Validation is completed after a push to main
  workflow_run:
    workflows:
      - 'Continuous Integration'
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    concurrency: nanlabs-splash-deployment
    environment: production
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          file_name: .env
          envkey_VITE_APP_BASE_URL: /nanlabs-splash/

      - name: Build page
        run: npm run build
        env:
          VITE_APP_BASE_URL: /nanlabs-splash/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
